DROP TABLE IF EXISTS order_items CASCADE;

CREATE TABLE order_items (
  id SERIAL PRIMARY KEY NOT NULL,
  orders_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  food_items_id INTEGER REFERENCES food_items(id) ON DELETE CASCADE,
  quantity INTEGER  NOT NULL DEFAULT 0,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  tax NUMERIC(10, 2) NOT NULL DEFAULT 0,
  special_request VARCHAR(255) NOT NULL
);